version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: next-pwa
    versions:
    - 5.0.6
    - 5.1.4
    - 5.2.1
    - 5.2.14
    - 5.2.3
    - 5.2.5
    - 5.2.9
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.2
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.2
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.3
  - dependency-name: framer-motion
    versions:
    - 3.10.0
    - 3.3.0
    - 3.5.2
    - 3.6.2
    - 3.6.7
    - 3.7.0
    - 3.9.0
    - 3.9.1
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.8
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.16
    - 6.1.18
    - 6.1.19
    - 6.1.20
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.16
    - 6.1.18
    - 6.1.19
    - 6.1.20
  - dependency-name: next
    versions:
    - 10.0.7
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
